package de.allround.kotlinweb.api.styles.styles

import de.allround.kotlinweb.api.styles.Style
import java.awt.Color
import java.awt.Font
import java.net.URL
import kotlin.time.Duration

@Suppress("unused")
class Styling(
    var selector: String, val styles: MutableList<Style> = mutableListOf()
) {
    fun append(style: Style) {
        styles.removeIf { it.name == style.name }
        styles.add(style)
    }

    override fun toString(): String {
        val builder = StringBuilder()

        builder.append(selector)

        builder.append(" {").append(System.lineSeparator())
        styles.forEach {
            builder.append(it.toString()).append(System.lineSeparator())
        }
        builder.append(" }")

        return builder.toString()
    }

    fun add(name: String, vararg value: Any): Style {
        styles.removeIf { it.name == name }
        val style = Style(name, value)
        append(style)
        return style
    }

    fun fontStyle(style: FontStyle): Style = add("font-style", style)
    fun fontVariant(variant: FontVariant): Style = add("font-variant", variant)
    fun fontWeight(weight: FontWeight): Style = add("font-weight", weight)
    fun fontSize(size: FontStyle): Style = add("font-size", size)
    fun fontSize(size: String): Style = add("font-size", size)
    fun fontFamily(font: Font): Style = add("font-family", font.family)
    fun fontFamily(family: String): Style = add("font-family", family)
    fun textAlign(align: TextAlign): Style = add("text-align", align)
    fun letterSpacing(space: LetterSpacing): Style = add("letter-spacing", space)
    fun letterSpacing(space: String): Style = add("letter-spacing", space)
    fun textOutline(outline: TextOutline): Style = add("text-outline", outline)
    fun textOutline(outline: Color): Style = add("text-outline", outline)
    fun wordWrap(wrap: WordWrap): Style = add("word-wrap", wrap)
    fun direction(textDirection: TextDirection): Style = add("direction", textDirection)
    fun textWrap(wrap: TextWrap): Style = add("text-wrap", wrap)
    fun textIndent(indent: String): Style = add("text-indent", indent)
    fun wordSpacing(spacing: String): Style = add("word-spacing", spacing)
    fun textTransform(transform: TextTransform): Style = add("text-transform", transform)
    fun textEmphasis(emphasis: TextEmphasis): Style = add("text-emphasis", emphasis)
    fun textJustify(justify: TextJustify): Style = add("text-justify", justify)
    fun appearance(appearance: Appearance): Style = add("appearance", appearance)
    fun cursor(cursor: Cursor): Style = add("cursor", cursor)
    fun navIndex(index: NavIndex): Style = add("nav-index", index)
    fun navIndex(index: Int): Style = add("nav-index", index)
    fun navUp(up: String): Style = add("nav-up", up)
    fun navDown(down: String): Style = add("nav-down", down)
    fun navLeft(left: String): Style = add("nav-left", left)
    fun navRight(right: String): Style = add("nav-right", right)
    fun resize(resize: Resize): Style = add("resize", resize)
    fun icon(icon: Icon): Style = add("icon", icon)
    fun icon(icon: URL): Style = add("icon", icon)
    fun backgroundSize(size: BackgroundSize): Style = add("background-size", size)
    fun backgroundSize(size: String): Style = add("background-size", size)
    fun backgroundImage(image: String): Style = add("background-image", image)
    fun backgroundRepeat(repeat: BackgroundRepeat): Style = add("background-repeat", repeat)
    fun backgroundAttachment(attachment: BackgroundAttachment): Style = add("background-attachment", attachment)
    fun backgroundColor(color: Color): Style = add("background-color", color)
    fun backgroundColorTransparent(): Style = add("background-color", "transparent")
    fun backgroundPosition(position: String): Style = add("background-position", position)
    fun backgroundOrigin(origin: String): Style = add("background-origin", origin)
    fun backgroundClip(clip: BackgroundClip): Style = add("background-clip", clip)
    fun backgroundClip(clip: String): Style = add("background-clip", clip)
    fun borderWidth(width: BorderWidth): Style = add("border-width", width)
    fun borderWidth(width: String): Style = add("border-width", width)
    fun borderStyle(style: BorderStyle): Style = add("border-style", style)
    fun borderColor(color: Color): Style = add("border-color", color)
    fun borderLeftWidth(left: BorderWidth): Style = add("border-left", left)
    fun borderRightWidth(right: BorderWidth): Style = add("border-right", right)
    fun borderTopWidth(top: BorderWidth): Style = add("border-top", top)
    fun borderBottomWidth(bottom: BorderWidth): Style = add("border-bottom", bottom)
    fun borderLeftWidth(left: String): Style = add("border-left", left)
    fun borderRightWidth(right: String): Style = add("border-right", right)
    fun borderTopWidth(top: String): Style = add("border-top", top)
    fun borderBottomWidth(bottom: String): Style = add("border-bottom", bottom)
    fun borderLeftColor(left: Color): Style = add("border-left", left)
    fun borderRightColor(right: Color): Style = add("border-right", right)
    fun borderTopColor(top: Color): Style = add("border-top", top)
    fun borderBottomColor(bottom: Color): Style = add("border-bottom", bottom)
    fun borderDecorationBreak(breakStyle: BorderDecorationBreak): Style = add("border-decoration-break", breakStyle)
    fun borderRadius(radius: String): Style = add("border-radius", radius)
    fun borderImage(image: BorderImage): Style = add("border-image", image)
    fun borderImage(image: String): Style = add("border-image", image)
    fun float(float: CSSFloat): Style = add("float", float)
    fun height(height: String): Style = add("height", height)
    fun maxHeight(height: String): Style = add("max-height", height)
    fun width(width: String): Style = add("width", width)
    fun maxWidth(width: String): Style = add("max-width", width)
    fun minHeight(height: String): Style = add("min-height", height)
    fun minWidth(width: String): Style = add("min-width", width)
    fun margin(margin: String): Style = add("margin", margin)
    fun marginBottom(margin: String): Style = add("margin-bottom", margin)
    fun marginLeft(margin: String): Style = add("margin-left", margin)
    fun marginRight(margin: String): Style = add("margin-right", margin)
    fun marginTop(margin: String): Style = add("margin-top", margin)
    fun padding(padding: String): Style = add("padding", padding)
    fun paddingBottom(padding: String): Style = add("padding-bottom", padding)
    fun paddingTop(padding: String): Style = add("padding-top", padding)
    fun paddingRight(padding: String): Style = add("padding-right", padding)
    fun paddingLeft(padding: String): Style = add("padding-left", padding)
    fun display(display: Display): Style = add("display", display)
    fun marqueeDirection(direction: MarqueeDirection): Style = add("marquee-direction", direction)
    fun marqueeLoop(loop: Int): Style = add("marquee-loop", if (loop < 0) "infinit" else loop)
    fun marqueePlayCount(count: Int): Style = add("marquee-play-count", if (count < 0) "infinit" else count)
    fun marqueeSpeed(speed: MarqueeSpeed): Style = add("marquee-speed", speed)
    fun marqueeStyle(style: MarqueeStyle): Style = add("marquee-style", style)
    fun overflow(overflow: Overflow): Style = add("overflow", overflow)
    fun overflowStyle(style: OverflowStyle): Style = add("overflow-style", style)
    fun overflowX(overflow: OverflowXY): Style = add("overflow-x", overflow)
    fun overflowY(overflow: OverflowXY): Style = add("overflow-y", overflow)
    fun rotation(rotation: String): Style = add("rotation", rotation)
    fun rotationPoint(x: String, y: String): Style = add("rotation-point", "$x $y")
    fun visibility(visibility: Visibility): Style = add("visibility", visibility)
    fun clear(clear: Clear): Style = add("clear", clear)
    fun boxAlign(align: BoxAlign): Style = add("box-align", align)
    fun boxDirection(direction: BoxDirection): Style = add("box-direction", direction)
    fun boxFlex(flex: String): Style = add("box-flex", flex)
    fun boxFlexGroup(group: Int): Style = add("box-flex-group", group)
    fun boxLines(lines: BoxLines): Style = add("box-lines", lines)
    fun boxOrient(orient: BoxOrient): Style = add("box-orient", orient)
    fun boxPack(pack: BoxPack): Style = add("box-pack", pack)
    fun boxSizing(sizing: BoxSizing): Style = add("box-sizing", sizing)
    fun tabSide(side: TabSide): Style = add("tab-side", side)
    fun borderCollapse(collapse: TableBorderCollapse): Style = add("border-collapse", collapse)
    fun emptyCells(cells: TableEmptyCell): Style = add("empty-cells", cells)
    fun borderSpacing(spacing: String): Style = add("border-spacing", spacing)
    fun tableLayout(layout: TableLayout): Style = add("table-layout", layout)
    fun captionSide(side: TableCaptionSide): Style = add("caption-side", side)
    fun columnCount(count: Int?): Style = add("column-count", count ?: "auto")
    fun columnFill(fill: ColumnFill): Style = add("column-fill", fill)
    fun columnGap(gap: String?): Style = add("column-gap", gap ?: "normal")
    fun columnRuleWidth(width: ColumnRuleWidth): Style = add("column-rule-width", width)
    fun columnRuleWidth(width: String): Style = add("column-rule-width", width)
    fun columnRuleStyle(style: OutlineStyle): Style = add("column-rule-style", style)
    fun columnRuleColor(color: Color): Style = add("column-rule-color", color)
    fun columnWidth(width: String?): Style = add("column-width", width ?: "auto")
    fun columnSpan(span: ColumnSpan): Style = add("column-span", span)
    fun color(color: Color?): Style = add("color", color ?: "inherit")
    fun opacity(opacity: String?): Style = add("opacity", opacity ?: "inherit")
    fun gridColumns(columns: Grid): Style = add("grid-columns", columns)
    fun gridRows(rows: Grid): Style = add("grid-rows", rows)
    fun gridColumns(columns: String): Style = add("grid-columns", columns)
    fun gridRows(rows: String): Style = add("grid-rows", rows)
    fun listStyleType(type: ListStyleType): Style = add("list-style-type", type)
    fun listStylePosition(position: String): Style = add("list-style-position", position)
    fun listStyleImage(image: URL?): Style = add("list-style-image", image ?: "none")
    fun markerOffset(offset: String?): Style = add("marker-offset", offset ?: "auto")
    fun animationName(name: String?): Style = add("animation-name", name ?: "none")
    fun animationDuration(duration: Duration): Style = add("animation-duration", "${duration.inWholeMilliseconds}ms")
    fun animationTimingFunction(function: TimingFunction): Style = add("animation-timing-function", function)
    fun animationDelay(delay: Duration): Style = add("animation-delay", "${delay.inWholeMilliseconds}ms")
    fun animationIterationCount(count: Int?): Style = add("animation-iteration-count", count ?: "inherit")
    fun animationDirection(direction: AnimationDirection): Style = add("animation-direction", direction)
    fun animationPlayState(state: Boolean): Style = add("animation-play-state", if (state) "running" else "paused")
    fun animationFillMode(mode: AnimationFillMode): Style = add("animation-fill-mode", mode)
    fun outlineColor(color: Color): Style = add("outline-color", color)
    fun outlineStyle(style: OutlineStyle): Style = add("outline-style", style)
    fun outlineWidth(width: BorderWidth): Style = add("outline-width", width)
    fun outlineWidth(width: String): Style = add("outline-width", width)
    fun outlineOffset(offset: String?): Style = add("outline-offset", offset ?: "inherit")
    fun targetName(name: TargetName): Style = add("target-name", name)
    fun targetName(name: String): Style = add("target-name", name)
    fun targetNew(new: TargetNew): Style = add("target-new", new)
    fun targetPosition(position: TargetPosition): Style = add("target-position", position)
    fun fit(fit: MediaFit): Style = add("fit", fit)
    fun fitPosition(first: MediaFitPosition, second: String): Style = add("fit-position", first, second)
    fun fitPosition(position: String): Style = add("fit-position", position)
    fun orphans(orphans: Int): Style = add("orphans", orphans)
    fun imageOrientation(orientation: String?): Style = add("image-orientation", orientation ?: "auto")
    fun page(page: String?): Style = add("page", page ?: "auto")
    fun pageBreakAfter(breakAfter: PageBreakAfter): Style = add("page-break-after", breakAfter)
    fun pageBreakBefore(breakBefore: PageBreakBefore): Style = add("page-break-before", breakBefore)
    fun pageBreakInside(breakInside: PageBreakInside): Style = add("page-break-inside", breakInside)
    fun size(size: MediaSize): Style = add("size", size)
    fun size(size: String): Style = add("size", size)
    fun windows(windows: Int): Style = add("windows", windows)
    fun bottom(bottom: String): Style = add("bottom", bottom)
    fun right(right: String): Style = add("right", right)
    fun top(top: String): Style = add("top", top)
    fun left(left: String): Style = add("left", left)
    fun zIndex(zIndex: Int?): Style = add("z-index", zIndex ?: "auto")
    fun clip(clip: Clip): Style = add("clip", clip)
    fun position(position: Position): Style = add("position", position)
    fun transitionsDelay(delay: Duration): Style = add("transitions-delay", "${delay.inWholeMilliseconds}ms")
    fun transitionsDuration(duration: Duration): Style =
        add("transitions-duration", "${duration.inWholeMilliseconds}ms")

    fun transitionsProperty(property: TransitionProperty): Style = add("transitions-property", property)
    fun transitionTimingFunction(timingFunction: TimingFunction): Style =
        add("transition-timing-function", timingFunction)

    fun transitionTimingFunction(first: Number, second: Number, third: Number, forth: Number): Style =
        add("transition-timing-function", "cubicBezier($first, $second, $third, $forth)")
}
